version: '3.8'  # You can omit this line if you don't want versioning

services:
  api:
    build:
    ports:
      - "${PORT:-3000}:3000"  # Map the container's port to the host port using an environment variable
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT:-3000}  # Set the PORT environment variable in the container

